import { CONTACT } from "./constants";
import type { GoogleReviewsData } from "./google-reviews";

/** Google reviews sourced from Lexis & Legis Law Associates Google Maps listing */
export const GOOGLE_REVIEWS: GoogleReviewsData = {
  rating: 5,
  totalReviews: 100,
  mapsUrl: CONTACT.googleReviewsUrl,
  reviews: [
    {
      author: "Adhikari Govinda",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Excellent service from start to finish. Communication was clear, and I felt confident knowing my legal issue was in good hands.",
    },
    {
      author: "Sameer Khanal",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Lexis Legis is the kind of law firm everyone hopes to find but rarely does. I honestly can't say enough good things about Lexis Legis. From day one, they made me feel comfortable and reassured during what was a really stressful time.",
    },
    {
      author: "Lok Raj Regmi",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Very knowledgeable, honest, and hardworking team. They exceeded my expectations with both the outcome and customer service. I highly recommend Lexis Legis law firm. Trustworthy, reliable, and effective. I'll definitely turn to them again if I ever need legal help.",
    },
    {
      author: "Target Upasachib",
      rating: 5,
      relativeTime: "10 months ago",
      text: "From my very first contact, the staff at this law firm were incredibly welcoming and professional. My primary contact with Mr. Sigdel was always courteous and efficient. The attorneys were highly knowledgeable but also very approachable.",
    },
    {
      author: "Aarati Aarati",
      rating: 5,
      relativeTime: "10 months ago",
      text: "I highly recommend Lexis and Legis Law Associates to anyone needing strong, experienced legal representation in criminal cases. They are not only experts in the field but also compassionate and respectful toward their clients.",
    },
    {
      author: "Julie Amilie",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Friendly, approachable, yet very sharp and effective in court. I felt fully confident with them by my side.",
    },
    {
      author: "Sunil Aryal",
      rating: 5,
      relativeTime: "8 months ago",
      text: "I recommend all to take required legal service from Lexis Legis. All advocates are friendly and trustworthy. They hear your legal problems and address it.",
    },
    {
      author: "Cheers United",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Very knowledgeable, honest, and hardworking team. They exceeded my expectations with both the outcome and customer service.",
    },
    {
      author: "Srijana Lamichhane",
      rating: 5,
      relativeTime: "9 months ago",
      text: "I highly recommend Lexis Legis law firm. Trustworthy, reliable, and effective. I'll definitely turn to them again if I ever need legal help.",
    },
    {
      author: "Asheem Aryal",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Outstanding law firm. They are thorough, strategic, and compassionate. I highly recommend them to anyone in need of legal help.",
    },
    {
      author: "Jhaman Aryal",
      rating: 5,
      relativeTime: "9 months ago",
      text: "The firm handled my matter quickly and efficiently. They explained all my options in simple terms, which made the process much less stressful.",
    },
    {
      author: "Shankar Yadav",
      rating: 5,
      relativeTime: "1 year ago",
      text: "My experience with Lexis and Legis Law Associates was incredibly positive! I can't emphasize enough how delighted I am with the exceptional service they delivered while helping me register my company. The entire team at this law firm showed top-notch professionalism and dedication.",
    },
    {
      author: "Rashmi Pahari",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Working with Lexis and Legis Law Associates was such a positive experience! I can't express how happy I am with the fantastic service they provided. The whole crew at this Law Firm really knew their stuff and showed top-notch professionalism, expertise, and dedication from start to finish.",
    },
    {
      author: "Khima Paudel",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Lexis and Legis Law Associates has provided the best guidance for matter on tax law. They have good knowledge and experience on corporate law including taxation.",
    },
    {
      author: "Laxmi Poudel",
      rating: 5,
      relativeTime: "9 months ago",
      text: "I had an excellent experience with this firm. They really know the law and are committed to achieving the best possible outcome.",
    },
    {
      author: "Kamala Pokhrel",
      rating: 5,
      relativeTime: "1 year ago",
      text: "One of the best law firm in Nepal. They have good knowledge in litigation and corporate matter. I definitely suggest Lexis and Legis Law Associates for getting legal consulting in Nepal.",
    },
    {
      author: "Ambika Poudel",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Clear communication, fair fees, and fantastic results. I can't thank Lexis Legis enough for what they did for me.",
    },
    {
      author: "Shishir Bastakoti",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Responsive, professional, and extremely supportive. They took the time to explain all the legal details so I always felt informed.",
    },
    {
      author: "Shiva Regmi",
      rating: 5,
      relativeTime: "5 months ago",
      text: "Best corporate law firm in Nepal.",
    },
    {
      author: "Khim Paudel",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Nepal. They are the best lawyers here in Kathmandu. They specialize in all kinds of cases mainly criminal and corporate cases.",
    },
    {
      author: "Manjil Baral",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Lexis and Legis Law Associates is a full service best law firm in Kathmandu. Good corporate lawyers in Nepal.",
    },
    {
      author: "Rashik Acharya",
      rating: 5,
      relativeTime: "1 year ago",
      text: "One of the best law firms in Nepal to provide expert legal services in the areas of Commercial, Criminal, Family, and Civil laws with our prominent criminal and corporate lawyers in Nepal. I was suggested by an agency to work with this Law Firm.",
    },
    {
      author: "Mukesh Aryal",
      rating: 5,
      relativeTime: "9 months ago",
      text: "This firm truly understands clients' needs. They brought clarity and comfort during a stressful process.",
    },
    {
      author: "Barun Lamsal",
      rating: 5,
      relativeTime: "9 months ago",
      text: "From the very first consultation, I knew I was working with professionals who truly cared about my situation.",
    },
    {
      author: "Bhakta Chhetri",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Lexis and Legis Law is best law firm in Nepal. Thank you so much Lexis and Legis Law for your best service. I recommended everyone to attend Lexis and Legis Law for legal service.",
    },
    {
      author: "Tejendra Paudel",
      rating: 5,
      relativeTime: "1 year ago",
      text: "I find Lexis and Legis Law Associates best law firm for criminal defense in Nepal. I was suggested by an agency to work with this Law Firm.",
    },
    {
      author: "Sarswati Khadka",
      rating: 5,
      relativeTime: "2 years ago",
      text: "I recommend this law firm to everyone to take their services as they provide genuine advice, prompt responses regarding any kind of matters which need to be fixed. You won't regret it, trust me. You will thank me later.",
    },
    {
      author: "Aashish Aryal",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Very knowledgeable, honest, and hardworking team. They exceeded my expectations with both the outcome and customer service.",
    },
    {
      author: "Pushpa Oli",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Nepal. The entire team is very professional and responsive.",
    },
    {
      author: "Jamuna Aryal",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Clear communication, fair rules and fantastic results. I can't thank Lexis Legis enough for what they did for me.",
    },
    {
      author: "Anup Lamsal",
      rating: 5,
      relativeTime: "9 months ago",
      text: "This firm truly understands clients' needs. They brought clarity and comfort during a stressful process.",
    },
    {
      author: "Ishwari Sharma",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Lexis and Legis Law Associates has provided the best guidance for matter on tax law. They have good knowledge and experience on corporate law including taxation.",
    },
    {
      author: "Durga Pokhrel",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Outstanding service in legal issues in the Himalayan Republic of Nepal.",
    },
    {
      author: "Saroj Khadka",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best corporate law firm in Kathmandu.",
    },
    {
      author: "Alisha Adhikari",
      rating: 5,
      relativeTime: "2 years ago",
      text: "I recommended everyone to attend Lexis and Legis Law for legal service.",
    },
    {
      author: "Roshan Timilsina",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Though the team is young, they have very very effective and efficient service.",
    },
    {
      author: "Nal Bahadur",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Nepal.",
    },
    {
      author: "Vikramaditya Singh",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Really good and intellectual.",
    },
    {
      author: "Dipendra Pariyar",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Kathmandu.",
    },
    {
      author: "Devilal Devkota",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Thank you for your good work on foreign investment.",
    },
    {
      author: "LokSewa Tayari",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Kathmandu.",
    },
    {
      author: "Nal Bahadur Nath",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Nepal.",
    },
    {
      author: "Bishwas Ghimire",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Good.",
    },
    {
      author: "Aabhas Aryal",
      rating: 5,
      relativeTime: "9 months ago",
      text: "Awesome.",
    },
    {
      author: "Aarati Poudel",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Got good service in foreign investment.",
    },
    {
      author: "Khima Paudel",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Contact for any legal advice! One of the best.",
    },
    {
      author: "Bibek Katwal",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Kathmandu.",
    },
    {
      author: "Kalpana Jaisi",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Nepal.",
    },
    {
      author: "Bishnu Maya Pokhrel",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Good intellectual property team.",
    },
    {
      author: "Sharma Alok",
      rating: 5,
      relativeTime: "1 year ago",
      text: "It's a blazing moment in the sector of justice.",
    },
    {
      author: "One Sweet",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Top Law Firm in Nepal.",
    },
    {
      author: "Lama Ut",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Best corporate law firm.",
    },
    {
      author: "Padevil",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Nepal.",
    },
    {
      author: "Sandes Anita",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Well Done Sir.",
    },
    {
      author: "Binita Kc",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm.",
    },
    {
      author: "Khema Nanda Pokhrel",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best corporate law firm.",
    },
    {
      author: "Sachin Sigdel",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Nepal.",
    },
    {
      author: "Binit Kaphle",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best service.",
    },
    {
      author: "Ala Ala",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best corporate law firm.",
    },
    {
      author: "Rajat Acharya",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Best law firm.",
    },
    {
      author: "Aarati Kumal",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best Law firm in Nepal.",
    },
    {
      author: "Firoz Box",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Best law firm.",
    },
    {
      author: "Sabin Basnet",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Nepal.",
    },
    {
      author: "Ashok Kumari Rai",
      rating: 5,
      relativeTime: "2 years ago",
      text: "Best Law Firm.",
    },
    {
      author: "Nitu Rauniyar",
      rating: 5,
      relativeTime: "2 months ago",
      text: "They handled my case smoothly and kept me updated throughout. Great experience.",
    },
    {
      author: "Rupesh Das",
      rating: 5,
      relativeTime: "2 months ago",
      text: "One of the best law firms in Kathmandu. Friendly and knowledgeable team.",
    },
    {
      author: "Avi Singh",
      rating: 5,
      relativeTime: "2 months ago",
      text: "Excellent service and very professional lawyers. Highly recommended!",
    },
    {
      author: "Begam Devkota",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Kathmandu Anamnagar Kathmandu.",
    },
    {
      author: "Mohan Paudel",
      rating: 5,
      relativeTime: "1 year ago",
      text: "Best law firm in Kathmandu Anamnagar.",
    },
  ],
};
