/** Primary Nepal-focused keywords (highest priority for rankings) */
export const PRIMARY_SEO_KEYWORDS = [
  "law firm in nepal",
  "law firm near me",
  "law firms in kathmandu",
  "law firm in kathmandu",
  "law firms in anamnagar",
  "law firm nepal",
  "legal firm in nepal",
  "law company in nepal",
  "law office in nepal",
  "lawyer firm in nepal",
  "best law firm in nepal",
  "corporate law firm in nepal",
  "top law firm in nepal",
  "criminal law firm in nepal",
  "leading law firm in nepal",
  "divorce law firm in nepal",
  "best corporate law firm in nepal",
  "law firm kathmandu",
  "law firm in nepali",
  "law firm meaning in nepali",
  "law firm registration in nepal",
  "law firm vacancy in kathmandu",
  "law firm vacancy in kathmandu for freshers",
  "law firm internships near me",
  "law firm internship",
  "international law firm in nepal",
  "biggest law firm in nepal",
  "big law firms in nepal",
  "law firm name in nepal",
  "how to become lawyer in nepal",
  "types of lawyers in nepal",
  "law salary in nepal",
  "highest paid lawyer in nepal",
] as const;

/** Extended keyword list for meta tags and discoverability */
export const SEO_KEYWORDS = [
  ...PRIMARY_SEO_KEYWORDS,
  "law firm meaning",
  "law firm in pokhara",
  "law firm websites",
  "law firm in bhaktapur",
  "law firm registration process",
  "law firm logo",
  "law firm in butwal",
  "law firm in biratnagar",
  "law firm name ideas",
  "law firm adalah",
  "law firm assistant jobs",
  "law firm associate",
  "law firm ai",
  "law firm accounting",
  "law firm administrator jobs",
  "law firm accounting jobs",
  "law firm associate salary",
  "law firm alliance",
  "law firm apprenticeships",
  "law firm admin jobs",
  "law firm ads",
  "law firm assistant",
  "law firm around me",
  "law firm administrator",
  "law firm board design",
  "law firm business cards",
  "law firm business development jobs",
  "law firm bangalore",
  "law firm billing software",
  "law firm brunei",
  "law firm birmingham",
  "law firm background",
  "law firm brochure",
  "law firm branding",
  "law firm billing jobs",
  "law firm building",
  "law firm bandung",
  "law firm bristol",
  "law firm baker mckenzie",
  "law firm carolinas",
  "law firm careers",
  "law firm chef",
  "law firm clerk",
  "law firm company",
  "law firm calgary",
  "law firm consultant",
  "law firm chicago",
  "law firm commercials",
  "law firm case management software",
  "law firm cover letter",
  "law firm chennai",
  "law firm clerk jobs",
  "law firm chandigarh",
  "law firm company profile",
  "law firm delhi",
  "law firm definition",
  "law firm dubai",
  "law firm downtown",
  "law firm directory",
  "law firm data breach",
  "law firm document management systems",
  "law firm dublin",
  "law firm dallas",
  "law firm delhi vacancy for freshers",
  "law firm dhaka",
  "law firm designations",
  "law firm dress code",
  "law firm davao",
  "law firm deadlines",
  "law firm entry level jobs",
  "law firm entry level jobs near me",
  "law firm examples",
  "law firm email",
  "law firm edmonton",
  "law firm executive orders",
  "law firm events",
  "law firm engagement letter",
  "law firm en español",
  "law firm employment",
  "law firm email address",
  "law firm economics",
  "law firm equity partner",
  "law firm employees",
  "law firm edinburgh",
  "law firm for sale",
  "law firm front desk jobs",
  "law firm for internship",
  "law firm for tenant rights",
  "law firm fonts",
  "law firm finance jobs",
  "law firm for truck safety",
  "law firm free consultation",
  "law firm for debt collection",
  "law firm florence sc",
  "law firm florida",
  "law firm flyer",
  "law firm fort worth",
  "law firm family law",
  "law firm for employment",
  "law firm gurgaon",
  "law firm gc",
  "law firm gone bust",
  "law firm group",
  "law firm ghaziabad",
  "law firm growth accelerator",
  "law firm glasgow",
  "law firm gibson dunn",
  "law firm greenville sc",
  "law firm guwahati",
  "law firm growth summit 2026",
  "law firm game",
  "law firm greensboro nc",
  "law firm grand rapids",
  "law firm guildford",
  "law firm hiring",
  "law firm hierarchy",
  "law firm hiring near me",
  "law firm houston",
  "law firm hyderabad",
  "law firm hr jobs",
  "law firm horvat",
  "law firm hk",
  "law firm hamilton",
  "law firm hiring receptionist",
  "law firm hhp",
  "law firm hierarchy uk",
  "law firm halifax",
  "law firm hierarchy usa",
  "law firm hotman paris",
  "law firm in babarmahal",
  "law firm in india",
  "law firm in spanish",
  "law firm in delhi",
  "law firm in usa",
  "law firm interview questions",
  "law firm in the philippines",
  "law firm jobs",
  "law firm jobs near me",
  "law firm jakarta",
  "law firm jobs in kolkata",
  "law firm jobs for undergraduate students",
  "law firm jobs in chandigarh for freshers",
  "law firm jobs in kolkata for freshers",
  "law firm jobs no experience",
  "law firm jobs for students",
  "law firm jobs entry level",
  "law firm job vacancy",
  "law firm jobs in delhi",
  "law firm johor bahru",
  "law firm jobs for freshers",
  "law firm jobs no degree",
  "law firm kolkata",
  "law firm kl",
  "law firm kdrama",
  "law firm kya hota hai",
  "law firm kirkland & ellis",
  "law firm kuching",
  "law firm kota kinabalu",
  "law firm kansas city",
  "law firm karachi",
  "law firm kuantan",
  "law firm kingston",
  "law firm kaise banaye",
  "law firm klang",
  "law firm kelowna",
  "law firm letterhead",
  "law firm layoffs",
  "law firm london",
  "law firm logo design",
  "law firm letterhead examples",
  "law firm logo ideas",
  "law firm los angeles",
  "law firm layoffs 2026",
  "law firm limited",
  "law firm letterhead sample",
  "law firm lagos",
  "law firm llc",
  "law firm list",
  "law firm letterhead template",
  "law firm marketing",
  "law firm mergers",
  "law firm marketing jobs",
  "law firm meaning in hindi",
  "law firm meaning in tamil",
  "law firm mumbai",
  "law firm management",
  "law firm mso",
  "law firm marketing agency",
  "law firm manila",
  "law firm meaning in bengali",
  "law firm malaysia",
  "law firm melbourne",
  "law firm management software",
  "law firm name",
  "law firm naics code",
  "law firm name generator",
  "law firm news",
  "law firm nyc",
  "law firm new york",
  "law firm noida",
  "law firm name examples",
  "law firm naics",
  "law firm newcastle",
  "law firm nearby",
  "law firm office",
  "law firm of alex dell",
  "law firm open days",
  "law firm of moumita rahman",
  "law firm of collection attorneys usa",
  "law firm of daniela labinoti p.c",
  "law firm of the year 2025",
  "law firm owner salary",
  "law firm of higbee & associates",
  "law firm office manager job description",
  "law firm open days 2026",
  "law firm of alex dell pllc",
  "law firm of the carolinas",
  "law firm or law firm",
  "law firm office manager salary",
  "law firm pronunciation",
  "law firm partner",
  "law firm partner salary",
  "law firm profits per partner 2025",
  "law firm profits per partner",
  "law firm positions",
  "law firm pictures",
  "law firm profits per partner 2026",
  "law firm profile",
  "law firm pune",
  "law firm partner meaning",
  "law firm penang",
  "law firm part time jobs",
  "law firm philippines",
  "law firm pay scale",
  "law firm questions to ask at interview",
  "law firm quinn emanuel",
  "law firm qatar",
  "law firm quotes",
  "law firm quartermaster",
  "law firm questions",
  "law firm queens",
  "law firm quezon city",
  "law firm queenstown",
  "law firm qualifications",
  "law firm quiz team names",
  "law firm quotation",
  "law firm quinn emanuel urquhart & sullivan",
  "law firm quotation sample",
  "law firm queen street",
  "law firm receptionist jobs",
  "law firm rankings",
  "law firm receptionist jobs near me",
  "law firm romance the attorney and the secretary",
  "law firm romance the attorney and the secretary cast",
  "law firm receptionist",
  "law firm rankings uk",
  "law firm recruitment",
  "law firm reviews",
  "law firm registration",
  "law firm rankings by revenue",
  "law firm remote jobs",
  "law firm research and innovation conference",
  "law firm runner jobs near me",
  "law firm seo",
  "law firm scholarships",
  "law firm singapore",
  "law firm salary",
  "law firm sic code",
  "law firm secretary jobs",
  "law firm scholarships for high school seniors",
  "law firm software",
  "law firm search",
  "law firm seo agency",
  "law firm series",
  "law firm structure",
  "law firm sydney",
  "law firm seo exults",
  "law firm services",
  "law firm toronto",
  "law firm terbaik di indonesia",
  "law firm tv shows",
  "law firm training contract",
  "law firm tv series",
  "law firm terbesar di indonesia",
  "law firm terdekat",
  "law firm titles",
  "law firm templates",
  "law firm tiers",
  "law firm tier list",
  "law firm trust account",
  "law firm tampa",
  "law firm toa payoh",
  "law firm usa",
  "law firm uk",
  "law firm using ai",
  "law firm undergraduate internships",
  "law firm us",
  "law firm uae",
  "law firm united",
  "law firm uniform",
  "law firm utilization rate",
  "law firm udaipur",
  "law firm uk rankings",
  "law firm union",
  "law firm under investigation",
  "law firm umhlanga",
  "law firm updates",
  "law firm vacancies",
  "law firm volunteer",
  "law firm vs law office",
  "law firm vancouver",
  "law firm vacancy in delhi",
  "law firm volunteer opportunities",
  "law firm vault rankings",
  "law firm vacancies near me",
  "law firm visiting card",
  "law firm vacation schemes",
  "law firm valuation",
  "law firm vs lawyer",
  "law firm velocity",
  "law firm work experience year 10",
  "law firm work experience year 12",
  "law firm work experience",
  "law firm work experience year 10 sydney",
  "law firm work experience year 10 london",
  "law firm website template",
  "law firm website design",
  "law firm work experience year 10 melbourne",
  "law firm work experience year 10 near me",
  "law firm work",
  "law firm with the most named partners",
  "law firm work experience near me",
  "law firm website usa",
  "law firm what is it",
  "law firm xcelerator",
  "law firm xyz",
  "law office xiao ji xiang esq",
  "law offices xuejie wong pllc",
  "ferguson law firm xenia ohio",
  "law firm of xavier solis kenosha",
  "law firm of xavier solis kenosha photos",
  "law firm of xavier solis photos",
  "fidelity law firm xiamen",
  "ferguson law firm xenia",
  "law firms in xenia ohio",
  "zimmerman reed law firm xfinity",
  "law firm york",
  "law firm year 10 work experience",
  "law firm year 12 work experience",
  "law firm yishun",
  "law firm yakup hasibuan",
  "law firm yogyakarta",
  "law firm yusril ihza mahendra",
  "law firm yerevan",
  "law firm yorkton",
  "law firm york pa",
  "law firm yonge and sheppard",
  "law firm yang & co",
  "law firm young",
  "law firm yangon",
  "law firm young and associates",
  "law firm zurich",
  "law firm zoom background",
  "law firm zimbabwe",
  "law firm zamboanga city",
  "law firm zambia",
  "law firm zba",
  "law firm zico",
  "law firm zachary",
  "law firm zap",
  "law practice za",
  "law office zamboanga city",
  "law office zoom background",
  "law office zulu ali",
  "law office zeqiri",
  "law office z",
  "how much does it cost to study law in nepal",
  "lexislegis",
  "lexis and legis",
  "law firm anamnagar",
  "consulting law firm nepal",
] as const;

export const DEFAULT_SITE_DESCRIPTION =
  "Lexislegis — best consulting and law firm in Nepal, Kathmandu (Anamnagar). Corporate law, litigation, divorce, family law, criminal defense, property law, NRN citizenship, internships and legal consultation. Law firm near me with 18+ practice areas.";
